{% set name = "kwant" %}
{% set version = "1.2.2" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://gitlab.kwant-project.org/kwant/kwant/repository/archive.tar.gz?ref=v{{ version }}
  sha256: d298791b920aa5a8191a83178e85472310db678b8237eaa928a8b2a347e825d8

build:
  skip: true  # [win or py2k]
  number: 201
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - toolchain
    - cython
    - gcc  # [osx]
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - mumps
    - numpy x.x
    - scipy
    - nose
    - tinyarray
    - libgfortran  # [linux]

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - mumps
    - numpy x.x
    - matplotlib
    - scipy
    - nose
    - tinyarray
    - libgfortran

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests

about:
  home: http://kwant-project.org/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Package for numerical quantum transport calculations.'
  description: |
    Kwant is a free (open source) Python package for numerical calculations on 
    tight-binding models with a strong focus on quantum transport. It is designed to 
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant 
    is often faster than other available codes, even those entirely written in the 
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
