appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GF84RU3CEwagbJ7SFTx9vEQm7NphWyuGCR5JEjd+B4dv4c1iHheyHKQk44v4iIVjmDCRCOj0zrzikS4al/x7ksRSfMMdYHR39CIWHEIEHvAgbf7/ZmvChPD4HeqNNp3ib8GXJku57HoOe/mF5enqMh2tiNXdE0f4fWXiU1fsqDrIufqrqVKAoC3F/soUxhfaMUXbwfLdDHFjRgefjQ1mAaCfXyAimmnh5qEt4EyGzlt0MlgmL3Gocuev1ECvPZE6kaNpVOslZISoT30CdptqYTmOIOdAttrhHdGteFh5XK718se29TeEpeYo5+ahcJw4nYhHeUQnueYaMz+KsuMOUjEagL/6NcmhdF0v5n+GI4/8hftTbfcgklxHbz0PlvFV8IQbatbpoD6Z8koGms8AWZuSg59fQ4bzPOpDPFQPgJDkmFevbALqC1swLMsTFvTuD3/Mih0FfyCSZYNTYz0MQtOjmalB0p35McQWjT9jpsYE0K52lCLFoHDhiUWqlF5Xo7JZmKO7uJyfU6fq3Vw3J13ZwKDNwXO4Em1clt1c2oMhFQaDDSx78aKwJ8hcQXwRcGnSpPGW5ffwyc5L37kJ4DPHY47Q6/lTa5NNASLOoQ8Dq+8oKUeiHNwakYeZgcKoOpxvVBDGujoTEAUXQnbOGTGDHFc2hMmBJvkeG5b3Fp4=}
